# Generated by Django 5.1 on 2024-08-28 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 5, 19, 4, 290002, tzinfo=datetime.timezone.utc)),
        ),
    ]
